programs:
  myprogram:
    cmd: "/workspaces/Taskmaster/workspaces/a.out"
    numprocs: 2
    umask: 33
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/myprogram.stdout
    stderr: /tmp/myprogram.stderr
    env:
      STARTED_BY: taskmaster
  
  myprogram2:
    cmd: "/workspaces/Taskmaster/workspaces/another.out"
    numprocs: 1
    umask: 0
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
    startretries: 20
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/myprogram.stdout
    stderr: /tmp/myprogram.stderr
    env:
      STARTED_BY: Taskmaster 2